all: processThreads summation execvExecution TCPServer TCPClient UDPServer UDPClient

processThreads: 32_HW1_Q1.c
	gcc -o processThreads 32_HW1_Q1.c -I.

summation: 32_HW1_Q2_Sum.c
	gcc -o summation 32_HW1_Q2_Sum.c -I.

execvExecution: 32_HW1_Q2.c
	gcc -o execvExecution 32_HW1_Q2.c -I.

TCPServer: 32_HW1_Q4_1_Server.c
	gcc -o TCPServer 32_HW1_Q4_1_Server.c -I.

TCPClient: 32_HW1_Q4_1_Client.c
	gcc -o TCPClient 32_HW1_Q4_1_Client.c -I.

UDPServer: 32_HW1_Q4_2_Server.c
	gcc -o UDPServer 32_HW1_Q4_2_Server.c -I.

UDPClient: 32_HW1_Q4_2_Client.c
	gcc -o UDPClient 32_HW1_Q4_2_Client.c -I.
